---
keep-yaml: true
title: Tidymodels with Guild AI
toc-title: Table of contents
---

Here is an example showing how to use *guildai* with tidymodels in R.

If this is your first exposure to *guildai*, we recommend starting with
the framework agnostic "Getting Started" guide. This example assumes
familiarity with guild concepts like *flags* and *scalars*.

We'll start with an example R script, named "train-tidymodels.R", that
trains, evaluates, and saves an tidymodels model using the "Ames
Housing" dataset. Here is what it looks like:

::: {.cell file="train-tidymodels.R"}
``` {.r .cell-code}
library(tidymodels)
library(butcher)
library(bestNormalize)
library(sessioninfo)

# Boilerplate options -------------------------------------------------
tidymodels_prefer()
theme_set(theme_bw())
options(pillar.advice = FALSE, pillar.min_title_chars = Inf)

# Setup and partition data --------------------------------------------
data(ames)

ames <-
  ames %>%
  mutate(Sale_Price = log10(Sale_Price)) %>%
  select(-contains("_Cond"))

ames_split <- initial_split(ames, strata = Sale_Price)
ames_not_test <- training(ames_split)
ames_test <- testing(ames_split)

ames_rs <- validation_split(ames_not_test, strata = Sale_Price)
ames_train <- analysis(ames_rs$splits[[1]])
ames_val <- assessment(ames_rs$splits[[1]])

# Flags ---------------------------------------------------------------

#| description: spline degrees of freedom for longitude
#| min: 2
#| max: 50
longitude_df <- 40L

#| description: spline degrees of freedom for latitude
#| min: 2
#| max: 50
latitude_df <- 40L

#| description: L2 penalty
#| min: 0.0
#| max: 1.0
pen_val <- 0.001

#| description: Mixture of L1 and L2 penalty
#| min: 0.0
#| max: 1.0
mix_val <- 1.0

# Recipe and Workflow -------------------------------------------------

ames_rec <-
  recipe(Sale_Price ~ ., data = ames_train) %>%
  step_other(MS_SubClass, MS_Zoning, Neighborhood, threshold = 0.05) %>%
  step_orderNorm(Lot_Area, ends_with("_SF"), Gr_Liv_Area) %>%
  step_dummy(all_nominal_predictors()) %>%
  step_interact(~ starts_with("Central"):Year_Built) %>%
  # NOTE We splice the values in via !! so that the step uses their values
  # and not a reference to global variables (a very bad idea)
  step_spline_natural(Longitude, deg_free = !!longitude_df) %>%
  step_spline_natural(Latitude, deg_free = !!latitude_df)

glmn_spec <-
  linear_reg(penalty = pen_val, mixture = mix_val) %>%
  set_engine("glmnet")

ames_wflow <-
  workflow() %>%
  add_model(glmn_spec) %>%
  add_recipe(ames_rec)

ames_fit <- fit(ames_wflow, data = ames_train)
ames_fit

# fit -----------------------------------------------------------------

glmnet_fit <-
  ames_fit %>%
  extract_fit_engine()

glmnet_pred <-
  glmnet_fit %>%
  coef(s = pen_val) %>%
  apply(2, function(x) sum(x != 0))

glmnet_fit %>% autoplot(best_penalty = pen_val)


# Validation set results ----------------------------------------------

ames_pred <- augment(ames_fit, ames_val)

ames_pred %>%
  ggplot(aes(Sale_Price, .pred)) +
  geom_abline(col = "green", lty = 2) +
  geom_point(alpha = 1 / 3) +
  coord_obs_pred() +
  labs(x = "Observed (log-10)", y = "Predicted (log-10)")

val_results <- ames_pred %>% metrics(Sale_Price, .pred)

cat('validation_rmse:', val_results$.estimate[1], "\n")
cat('validation_R2:', val_results$.estimate[2], "\n")
cat('num_predictors:', glmnet_pred, "\n")

# Save object ---------------------------------------------------------

# butcher the objects to make their install sizes smaller
ames_fit <- butcher(ames_fit)

# Save objects in the current working directory
save(ames_fit, val_results, file = ".RData",
     compress = TRUE)

# ---------------------------------------------------------------------

session_info()
```
:::

A few things to note about the script:

-   There is no 'guildai' specific configuration in the script code.
    It's a regular R script, that you can safely `source()` or work with
    interactively at the REPL.
-   We declare some constraints on the flag values we've defined.
-   At the end of the run, we save the model. This file artifacts will
    be stored as part of the run, enabling us to restore a trained
    model.

With our script defined, we can launch a guild run and view it:

::: cell
``` {.r .cell-code}
library(guildai)
guild_run("train-tidymodels.R")
## > library(tidymodels)
## ── Attaching packages ────────────────────────────────────── tidymodels 1.0.0 ──
## ✔ broom        1.0.2      ✔ recipes      1.0.4 
## ✔ dials        1.1.0      ✔ rsample      1.1.1 
## ✔ dplyr        1.0.10     ✔ tibble       3.1.8 
## ✔ ggplot2      3.4.0      ✔ tidyr        1.2.1 
## ✔ infer        1.0.4      ✔ tune         1.0.1 
## ✔ modeldata    1.0.1      ✔ workflows    1.1.2 
## ✔ parsnip      1.0.3      ✔ workflowsets 1.0.0 
## ✔ purrr        1.0.1      ✔ yardstick    1.1.0 
## ── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
## ✖ purrr::discard() masks scales::discard()
## ✖ dplyr::filter()  masks stats::filter()
## ✖ dplyr::lag()     masks stats::lag()
## ✖ recipes::step()  masks stats::step()
## • Learn how to get started at https://www.tidymodels.org/start/
## > library(butcher)
## > library(bestNormalize)
## > library(sessioninfo)
## > # Boilerplate options -------------------------------------------------
## > tidymodels_prefer()
## > theme_set(theme_bw())
## > options(pillar.advice = FALSE, pillar.min_title_chars = Inf)
## > # Setup and partition data --------------------------------------------
## > data(ames)
## > ames <-
## +   ames %>%
## +   mutate(Sale_Price = log10(Sale_Price)) %>%
## +   select(-contains("_Cond"))
## > ames_split <- initial_split(ames, strata = Sale_Price)
## > ames_not_test <- training(ames_split)
## > ames_test <- testing(ames_split)
## > ames_rs <- validation_split(ames_not_test, strata = Sale_Price)
## > ames_train <- analysis(ames_rs$splits[[1]])
## > ames_val <- assessment(ames_rs$splits[[1]])
## > # Flags ---------------------------------------------------------------
## > 
## > #| description: spline degrees of freedom for longitude
## > #| min: 2
## > #| max: 50
## > longitude_df <- 40L
## > #| description: spline degrees of freedom for latitude
## > #| min: 2
## > #| max: 50
## > latitude_df <- 40L
## > #| description: L2 penalty
## > #| min: 0.0
## > #| max: 1.0
## > pen_val <- 0.001
## > #| description: Mixture of L1 and L2 penalty
## > #| min: 0.0
## > #| max: 1.0
## > mix_val <- 1.0
## > # Recipe and Workflow -------------------------------------------------
## > 
## > ames_rec <-
## +   recipe(Sale_Price ~ ., data = ames_train) %>%
## +   step_other(MS_SubClass, MS_Zoning, Neighborhood, threshold = 0.05) %>%
## +   step_orderNorm(Lot_Area, ends_with("_SF"), Gr_Liv_Area) %>%
## +   step_dummy(all_nominal_predictors()) %>%
## +   step_interact(~ starts_with("Central"):Year_Built) %>%
## +   # NOTE We splice the values in via !! so that the step uses their values
## +   # and not a reference to global variables (a very bad idea)
## +   step_spline_natural(Longitude, deg_free = !!longitude_df) %>%
## +   step_spline_natural(Latitude, deg_free = !!latitude_df)
## > glmn_spec <-
## +   linear_reg(penalty = pen_val, mixture = mix_val) %>%
## +   set_engine("glmnet")
## > ames_wflow <-
## +   workflow() %>%
## +   add_model(glmn_spec) %>%
## +   add_recipe(ames_rec)
## > ames_fit <- fit(ames_wflow, data = ames_train)
## Warning in object$object : partial match of 'object' to 'objects'
## Warning in object$object : partial match of 'object' to 'objects'
## > ames_fit
## ══ Workflow [trained] ══════════════════════════════════════════════════════════
## Preprocessor: Recipe
## Model: linear_reg()
## 
## ── Preprocessor ────────────────────────────────────────────────────────────────
## 6 Recipe Steps
## 
## • step_other()
## • step_orderNorm()
## • step_dummy()
## • step_interact()
## • step_spline_natural()
## • step_spline_natural()
## 
## ── Model ───────────────────────────────────────────────────────────────────────
## Warning in seq.default(along = x$df) :
##   partial argument match of 'along' to 'along.with'
## 
## Call:  glmnet::glmnet(x = maybe_matrix(x), y = y, family = "gaussian",      alpha = ~mix_val) 
## 
##      Df  %Dev           Lambda
## 1     0  0.00 0.12518364563700
## 2     2  9.64 0.11406267558000
## 3     2 19.39 0.10392966185100
## 4     3 27.84 0.09469683713430
## 5     4 36.50 0.08628423111870
## 6     4 43.76 0.07861897783540
## 7     5 49.83 0.07163468452750
## 8     5 55.14 0.06527085658750
## 9     5 59.54 0.05947237358230
## 10    5 63.19 0.05418901182600
## 11    5 66.23 0.04937500936660
## 12    6 68.76 0.04498866961770
## 13    6 70.86 0.04099200020280
## 14    6 72.61 0.03735038388350
## 15    7 74.26 0.03403227872120
## 16    7 75.65 0.03100894487650
## 17    8 76.88 0.02825419567790
## 18    8 77.91 0.02574417080570
## 19    8 78.77 0.02345712962530
## 20    8 79.48 0.02137326287990
## 21   10 80.09 0.01947452111280
## 22   12 80.72 0.01774445833120
## 23   13 81.38 0.01616808955880
## 24   14 82.01 0.01473176104350
## 25   17 82.66 0.01342303199490
## 26   17 83.22 0.01223056682790
## 27   23 83.75 0.01114403697970
## 28   26 84.30 0.01015403144870
## 29   26 84.76 0.00925197528049
## 30   30 85.17 0.00843005529609
## 31   33 85.66 0.00768115241779
## 32   34 86.09 0.00699878000714
## 33   36 86.47 0.00637702768075
## 34   39 86.80 0.00581051011742
## 35   44 87.14 0.00529432041302
## 36   46 87.46 0.00482398757929
## 37   50 87.78 0.00439543781821
## 38   53 88.11 0.00400495923677
## 39   56 88.40 0.00364916969631
## 40   60 88.67 0.00332498751802
## 41   64 88.90 0.00302960479097
## 42   66 89.12 0.00276046305128
## 43   69 89.32 0.00251523112196
## 44   81 89.51 0.00229178492135
## 45   87 89.70 0.00208818906536
## 46   90 89.88 0.00190268010409
## 
## ...
## and 54 more lines.
## > # fit -----------------------------------------------------------------
## > 
## > glmnet_fit <-
## +   ames_fit %>%
## +   extract_fit_engine()
## > glmnet_pred <-
## +   glmnet_fit %>%
## +   coef(s = pen_val) %>%
## +   apply(2, function(x) sum(x != 0))
## Warning in seq.default(along = s) :
##   partial argument match of 'along' to 'along.with'
## > glmnet_fit %>% autoplot(best_penalty = pen_val)
## > # Validation set results ----------------------------------------------
## > 
## > ames_pred <- augment(ames_fit, ames_val)
## Warning in object$object : partial match of 'object' to 'objects'
## Warning in object$object : partial match of 'object' to 'objects'
## Warning in seq.default(along = s) :
##   partial argument match of 'along' to 'along.with'
## > ames_pred %>%
## +   ggplot(aes(Sale_Price, .pred)) +
## +   geom_abline(col = "green", lty = 2) +
## +   geom_point(alpha = 1 / 3) +
## +   coord_obs_pred() +
## +   labs(x = "Observed (log-10)", y = "Predicted (log-10)")
## > val_results <- ames_pred %>% metrics(Sale_Price, .pred)
## > cat('validation_rmse:', val_results$.estimate[1], "\n")
## validation_rmse: 0.072934713351508 
## > cat('validation_R2:', val_results$.estimate[2], "\n")
## validation_R2: 0.84700967677576 
## > cat('num_predictors:', glmnet_pred, "\n")
## num_predictors: 125 
## > # Save object ---------------------------------------------------------
## > 
## > # butcher the objects to make their install sizes smaller
## > ames_fit <- butcher(ames_fit)
## > # Save objects in the current working directory
## > save(ames_fit, val_results, file = ".RData",
## +      compress = TRUE)
## > # ---------------------------------------------------------------------
## > 
## > session_info()
## ─ Session info ───────────────────────────────────────────────────────────────
##  setting  value
##  version  R version 4.2.1 (2022-06-23)
##  os       Ubuntu 20.04.5 LTS
##  system   x86_64, linux-gnu
##  ui       X11
##  language (EN)
##  collate  en_US.UTF-8
##  ctype    en_US.UTF-8
##  tz       America/New_York
##  date     2023-01-23
##  pandoc   2.5 @ /usr/bin/pandoc
## 
## ─ Packages ───────────────────────────────────────────────────────────────────
##  package       * version    date (UTC) lib source
##  assertthat      0.2.1      2019-03-21 [1] CRAN (R 4.2.1)
##  backports       1.4.1      2021-12-13 [1] CRAN (R 4.2.1)
##  bestNormalize * 1.8.3      2022-06-13 [1] CRAN (R 4.2.1)
##  broom         * 1.0.2      2022-12-15 [1] CRAN (R 4.2.1)
##  butcher       * 0.3.1      2022-12-14 [1] CRAN (R 4.2.1)
##  cachem          1.0.6      2021-08-19 [1] CRAN (R 4.2.1)
##  class           7.3-20     2022-01-16 [2] CRAN (R 4.2.1)
##  cli             3.6.0      2023-01-09 [1] CRAN (R 4.2.1)
##  codetools       0.2-18     2020-11-04 [2] CRAN (R 4.2.1)
##  colorspace      2.0-3      2022-02-21 [1] CRAN (R 4.2.1)
##  conflicted      1.1.0      2021-11-26 [1] CRAN (R 4.2.1)
##  DBI             1.1.3      2022-06-18 [1] CRAN (R 4.2.1)
##  dials         * 1.1.0      2022-11-04 [1] CRAN (R 4.2.1)
##  DiceDesign      1.9        2021-02-13 [1] CRAN (R 4.2.1)
##  digest          0.6.31     2022-12-11 [1] CRAN (R 4.2.1)
##  doParallel      1.0.17     2022-02-07 [1] CRAN (R 4.2.1)
##  doRNG           1.8.6      2023-01-16 [1] CRAN (R 4.2.1)
##  dplyr         * 1.0.10     2022-09-01 [1] CRAN (R 4.2.1)
##  ellipsis        0.3.2      2021-04-29 [1] CRAN (R 4.2.1)
##  fansi           1.0.3      2022-03-24 [1] CRAN (R 4.2.1)
##  farver          2.1.1      2022-07-06 [1] CRAN (R 4.2.1)
##  fastmap         1.1.0      2021-01-25 [1] CRAN (R 4.2.1)
##  foreach         1.5.2      2022-02-02 [1] CRAN (R 4.2.1)
##  furrr           0.3.1      2022-08-15 [1] CRAN (R 4.2.1)
##  future          1.30.0     2022-12-16 [1] CRAN (R 4.2.1)
##  future.apply    1.10.0     2022-11-05 [1] CRAN (R 4.2.1)
##  generics        0.1.3      2022-07-05 [1] CRAN (R 4.2.1)
##  ggplot2       * 3.4.0      2022-11-04 [1] CRAN (R 4.2.1)
##  ggrepel         0.9.2      2022-11-06 [1] CRAN (R 4.2.1)
##  glmnet          4.1-6      2022-11-27 [1] CRAN (R 4.2.1)
##  globals         0.16.2     2022-11-21 [1] CRAN (R 4.2.1)
##  glue            1.6.2      2022-02-24 [1] CRAN (R 4.2.1)
##  gower           1.0.1      2022-12-22 [1] CRAN (R 4.2.1)
##  GPfit           1.0-8      2019-02-08 [1] CRAN (R 4.2.1)
##  gtable          0.3.1      2022-09-01 [1] CRAN (R 4.2.1)
##  guildai         0.0.0.9001 2023-01-23 [1] local
##  hardhat         1.2.0      2022-06-30 [1] CRAN (R 4.2.1)
##  infer         * 1.0.4      2022-12-02 [1] CRAN (R 4.2.1)
##  ipred           0.9-13     2022-06-02 [1] CRAN (R 4.2.1)
##  iterators       1.0.14     2022-02-05 [1] CRAN (R 4.2.1)
##  jsonlite        1.8.4      2022-12-06 [1] CRAN (R 4.2.1)
##  labeling        0.4.2      2020-10-20 [1] CRAN (R 4.2.1)
##  lattice         0.20-45    2021-09-22 [2] CRAN (R 4.2.1)
##  lava            1.7.1      2023-01-06 [1] CRAN (R 4.2.1)
##  lhs             1.1.6      2022-12-17 [1] CRAN (R 4.2.1)
##  lifecycle       1.0.3      2022-10-07 [1] CRAN (R 4.2.1)
##  listenv         0.9.0      2022-12-16 [1] CRAN (R 4.2.1)
##  lubridate       1.9.0      2022-11-06 [1] CRAN (R 4.2.1)
##  magrittr        2.0.3      2022-03-30 [1] CRAN (R 4.2.1)
##  MASS            7.3-58.1   2022-08-03 [2] CRAN (R 4.2.1)
##  Matrix          1.5-3      2022-11-11 [2] CRAN (R 4.2.1)
##  memoise         2.0.1      2021-11-26 [1] CRAN (R 4.2.1)
##  modeldata     * 1.0.1      2022-09-06 [1] CRAN (R 4.2.1)
##  munsell         0.5.0      2018-06-12 [1] CRAN (R 4.2.1)
##  nnet            7.3-18     2022-09-28 [2] CRAN (R 4.2.1)
##  nortest         1.0-4      2015-07-30 [1] CRAN (R 4.2.1)
##  parallelly      1.34.0     2023-01-13 [1] CRAN (R 4.2.1)
##  parsnip       * 1.0.3      2022-11-11 [1] CRAN (R 4.2.1)
##  pillar          1.8.1      2022-08-19 [1] CRAN (R 4.2.1)
##  pkgconfig       2.0.3      2019-09-22 [1] CRAN (R 4.2.1)
##  prodlim         2019.11.13 2019-11-17 [1] CRAN (R 4.2.1)
##  purrr         * 1.0.1      2023-01-10 [1] CRAN (R 4.2.1)
##  R6              2.5.1      2021-08-19 [1] CRAN (R 4.2.1)
##  Rcpp            1.0.9      2022-07-08 [1] CRAN (R 4.2.1)
##  recipes       * 1.0.4      2023-01-11 [1] CRAN (R 4.2.1)
##  rlang           1.0.6      2022-09-24 [1] CRAN (R 4.2.1)
##  rngtools        1.5.2      2021-09-20 [1] CRAN (R 4.2.1)
##  rpart           4.1.19     2022-10-21 [2] CRAN (R 4.2.1)
##  rsample       * 1.1.1      2022-12-07 [1] CRAN (R 4.2.1)
##  rstudioapi      0.14       2022-08-22 [1] CRAN (R 4.2.1)
##  scales        * 1.2.1      2022-08-20 [1] CRAN (R 4.2.1)
##  sessioninfo   * 1.2.2      2021-12-06 [1] CRAN (R 4.2.1)
##  shape           1.4.6      2021-05-19 [1] CRAN (R 4.2.1)
##  splines2        0.4.7      2023-01-14 [1] CRAN (R 4.2.1)
##  survival        3.5-0      2023-01-09 [2] CRAN (R 4.2.1)
##  tibble        * 3.1.8      2022-07-22 [1] CRAN (R 4.2.1)
##  tidymodels    * 1.0.0      2022-07-13 [1] CRAN (R 4.2.1)
##  tidyr         * 1.2.1      2022-09-08 [1] CRAN (R 4.2.1)
##  tidyselect      1.2.0      2022-10-10 [1] CRAN (R 4.2.1)
##  timechange      0.2.0      2023-01-11 [1] CRAN (R 4.2.1)
##  timeDate        4022.108   2023-01-07 [1] CRAN (R 4.2.1)
##  tune          * 1.0.1      2022-10-09 [1] CRAN (R 4.2.1)
##  utf8            1.2.2      2021-07-24 [1] CRAN (R 4.2.1)
##  vctrs           0.5.1      2022-11-16 [1] CRAN (R 4.2.1)
##  withr           2.5.0      2022-03-03 [1] CRAN (R 4.2.1)
##  workflows     * 1.1.2      2022-11-16 [1] CRAN (R 4.2.1)
##  workflowsets  * 1.0.0      2022-07-12 [1] CRAN (R 4.2.1)
##  yaml            2.3.6      2022-10-18 [1] CRAN (R 4.2.1)
##  yardstick     * 1.1.0      2022-09-07 [1] CRAN (R 4.2.1)
## 
##  [1] /home/tomasz/opt/R-4.2.1/lib/R/site-library
##  [2] /home/tomasz/opt/R-4.2.1/lib/R/library
## 
## ──────────────────────────────────────────────────────────────────────────────
```
:::

::: cell
``` {.r .cell-code}
guild_view()
```
:::

We can use the flags and flag constraints to run an optimizer. We could
use one of the guildai built-in optimizers, or manually define a grid
using tidymodels functions, like this:

::: {.cell paged.print="false"}
``` {.r .cell-code}
# Use existing tidymodels code to generate a space-filling design for
# new hyperparameter combinations
library(tidymodels)
## ── Attaching packages ────────────────────────────────────── tidymodels 1.0.0 ──
## ✔ broom        1.0.2      ✔ recipes      1.0.4 
## ✔ dials        1.1.0      ✔ rsample      1.1.1 
## ✔ dplyr        1.0.10     ✔ tibble       3.1.8 
## ✔ ggplot2      3.4.0      ✔ tidyr        1.2.1 
## ✔ infer        1.0.4      ✔ tune         1.0.1 
## ✔ modeldata    1.0.1      ✔ workflows    1.1.2 
## ✔ parsnip      1.0.3      ✔ workflowsets 1.0.0 
## ✔ purrr        1.0.1      ✔ yardstick    1.1.0
## ── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
## ✖ purrr::discard() masks scales::discard()
## ✖ dplyr::filter()  masks stats::filter()
## ✖ dplyr::lag()     masks stats::lag()
## ✖ recipes::step()  masks stats::step()
## • Dig deeper into tidy modeling with R at https://www.tmwr.org
params <- parameters(list(
  pen_val = penalty(),
  mix_val = mixture(),
  latitude_df = spline_degree(c(2L, 50L)),
  longitude_df = spline_degree(c(2L, 50L))
))

set.seed(1)
grid <- grid_latin_hypercube(params, size = 19)
grid
## # A tibble: 19 × 4
##     pen_val mix_val latitude_df longitude_df
##       <dbl>   <dbl>       <int>        <int>
##  1 1.10e- 8  0.915           21           31
##  2 3.88e- 3  0.289           29            2
##  3 1.11e- 7  0.996           25            5
##  4 1.57e- 4  0.480           37           26
##  5 1.00e- 3  0.568           47           29
##  6 3.10e- 9  0.0644           4           12
##  7 2.54e-10  0.841            6           37
##  8 1.13e- 1  0.401           50           44
##  9 6.15e- 7  0.633           15           38
## 10 1.81e- 5  0.254           41           49
## 11 5.81e- 5  0.363           32            7
## 12 6.53e- 1  0.0346          19           24
## 13 4.48e- 4  0.879           38           42
## 14 4.15e- 2  0.613           14           13
## 15 1.06e- 9  0.457           11           35
## 16 1.83e- 2  0.777            8           21
## 17 2.96e- 6  0.174           42           46
## 18 2.81e- 8  0.690           34           16
## 19 3.40e- 7  0.157           26           20

# Launch a batch of run defined by the grid flags.
guild_run(
  "train-tidymodels.R",
  flags = grid,
  echo = c(FALSE, FALSE) # ignore stdout *and* stderr
)
```
:::

Find the best run:

::: {.cell paged.print="false"}
``` {.r .cell-code}
runs <- runs_info(operation = "train-tidymodels.R")

runs$scalars
## # A tibble: 20 × 3
##    num_predictors validation_R2 validation_rmse
##             <dbl>         <dbl>           <dbl>
##  1            199         0.841          0.0747
##  2            204         0.845          0.0723
##  3            203         0.854          0.0691
##  4             21         0.840          0.0779
##  5            195         0.869          0.0639
##  6             12         0.791          0.0922
##  7            170         0.866          0.0643
##  8             46         0.815          0.105 
##  9            198         0.805          0.0796
## 10            203         0.839          0.0727
## 11            199         0.883          0.0594
## 12             11         0.772          0.121 
## 13            203         0.877          0.0638
## 14            199         0.886          0.0619
## 15            143         0.880          0.0643
## 16            192         0.866          0.0626
## 17            209         0.871          0.0646
## 18            123         0.825          0.0772
## 19            200         0.808          0.0811
## 20            125         0.847          0.0729
```
:::

::: {.cell paged.print="false"}
``` {.r .cell-code}
best_run <- runs %>%
  slice_min(scalars$validation_rmse)
```
:::

Recover the fitted model and validation from the best run:

::: {.cell paged.print="false"}
``` {.r .cell-code}
best_run_saved_objects <- new.env(parent = emptyenv())
load(file.path(best_run$dir, ".RData"),
     envir = best_run_saved_objects)

best_run_saved_objects$ames_fit
## ══ Workflow [trained] ══════════════════════════════════════════════════════════
## Preprocessor: Recipe
## Model: linear_reg()
## 
## ── Preprocessor ────────────────────────────────────────────────────────────────
## 6 Recipe Steps
## 
## • step_other()
## • step_orderNorm()
## • step_dummy()
## • step_interact()
## • step_spline_natural()
## • step_spline_natural()
## 
## ── Model ───────────────────────────────────────────────────────────────────────
##   [[ suppressing 100 column names 's0', 's1', 's2' ... ]]
## $a0
##       s0       s1       s2       s3       s4       s5       s6       s7 
## 5.221977 5.219038 5.206302 5.063893 4.831120 4.496724 4.132204 3.793672 
##       s8       s9      s10      s11      s12      s13      s14      s15 
## 3.480007 3.189700 2.921091 2.665900 2.424669 2.200835 2.017582 1.869450 
##      s16      s17      s18      s19      s20      s21      s22      s23 
## 1.732038 1.605971 1.490381 1.391229 1.303487 1.263113 1.258430 1.251945 
##      s24      s25      s26      s27      s28      s29      s30      s31 
## 1.248986 1.252991 1.259436 1.280399 1.295894 1.307214 1.330520 1.369533 
##      s32      s33      s34      s35      s36      s37      s38      s39 
## 1.399861 1.424377 1.438443 1.452286 1.458205 1.459068 1.464233 1.467904 
##      s40      s41      s42      s43      s44      s45      s46      s47 
## 1.474059 1.475048 1.474604 1.481347 1.633967 1.865457 2.078415 2.291629 
##      s48      s49      s50      s51      s52      s53      s54      s55 
## 2.483996 2.659209 2.809554 2.963159 3.098229 3.211739 3.345793 3.490232 
##      s56      s57      s58      s59      s60      s61      s62      s63 
## 3.623644 3.756166 3.891477 4.021465 4.151451 4.276857 4.385500 4.483382 
##      s64      s65      s66      s67      s68      s69      s70      s71 
## 4.570927 4.667317 4.756276 4.844513 4.928317 5.001113 5.069161 5.163413 
##      s72      s73      s74      s75      s76      s77      s78      s79 
## 5.225653 5.297274 5.345470 5.385847 5.425880 5.455914 5.487505 5.524146 
##      s80      s81      s82      s83      s84      s85      s86      s87 
## 5.552352 5.581117 5.610014 5.634489 5.656176 5.677039 5.695473 5.712509 
##      s88      s89      s90      s91      s92      s93      s94      s95 
## 5.728882 5.739164 5.756507 5.773788 5.784120 5.793478 5.802923 5.813058 
##      s96      s97      s98      s99 
## 5.819573 5.825663 5.831184 5.836182 
## 
## $beta
## 215 x 100 sparse Matrix of class "dgCMatrix"
##                                                                         
## Lot_Frontage                                     . .          .         
## Lot_Area                                         . .          .         
## Year_Built                                       . .          .         
## Year_Remod_Add                                   . .          .         
## Mas_Vnr_Area                                     . .          .         
## BsmtFin_SF_1                                     . .          .         
## BsmtFin_SF_2                                     . .          .         
## Bsmt_Unf_SF                                      . .          .         
## Total_Bsmt_SF                                    . .          .         
## First_Flr_SF                                     . .          .         
## Second_Flr_SF                                    . .          .         
## Gr_Liv_Area                                      . 0.00761501 0.01331084
## Bsmt_Full_Bath                                   . .          .         
## Bsmt_Half_Bath                                   . .          .         
## Full_Bath                                        . .          .         
## Half_Bath                                        . .          .         
## Bedroom_AbvGr                                    . .          .         
## Kitchen_AbvGr                                    . .          .         
## TotRms_AbvGrd                                    . .          .         
## 
## ...
## and 18631 more lines.

best_run_saved_objects$val_results
## # A tibble: 3 × 3
##   .metric .estimator .estimate
##   <chr>   <chr>          <dbl>
## 1 rmse    standard      0.0594
## 2 rsq     standard      0.883 
## 3 mae     standard      0.0407
```
:::

For reproducibility, (or preparing to deploy a model) it can be helpful
to know some additional run metadata, like the starting random seed or a
log of which R packages were loaded during the R session. This
information is all stored under the `RUN_DIR/.guild` directory.

To recover the seed:

::: cell
``` {.r .cell-code}
run <- best_run
seed <- yaml::read_yaml(file.path(run$dir, ".guild/attrs/random_seed"))
seed
## [1] 193566307
set.seed(seed) # restore the starting seed.
```
:::

To access the log of R loaded packages:

::: cell
``` {.r .cell-code}
packages_loaded <- yaml::read_yaml(
  file.path(run$dir, ".guild/attrs/r_packages_loaded"))
str(packages_loaded, list.len = 5)
## List of 100
##  $ guildai      :List of 2
##   ..$ path   : chr "/home/tomasz/opt/R-4.2.1/lib/R/site-library/guildai"
##   ..$ version: chr "0.0.0.9001"
##  $ grDevices    :List of 2
##   ..$ path   : chr "/home/tomasz/opt/R-4.2.1/lib/R/library/grDevices"
##   ..$ version: chr "4.2.1"
##  $ fansi        :List of 2
##   ..$ path   : chr "/home/tomasz/opt/R-4.2.1/lib/R/site-library/fansi"
##   ..$ version: chr "1.0.3"
##  $ assertthat   :List of 2
##   ..$ path   : chr "/home/tomasz/opt/R-4.2.1/lib/R/site-library/assertthat"
##   ..$ version: chr "0.2.1"
##  $ utf8         :List of 2
##   ..$ path   : chr "/home/tomasz/opt/R-4.2.1/lib/R/site-library/utf8"
##   ..$ version: chr "1.2.2"
##   [list output truncated]
```
:::
